#!/bin/bash

echo "//Autogenerated offsets from kallsyms" > offsets.h

TEMP=`sudo grep " sys_call_table$" /proc/kallsyms`
TEMP2=($TEMP)
echo "Setting SYS_CALL_TABLE_ADDR = ${TEMP2[0]}"
echo "#define SYS_CALL_TABLE_ADDR 0x${TEMP2[0]}" >> offsets.h

TEMP=`sudo grep " putname$" /proc/kallsyms`
TEMP2=($TEMP)
echo "Setting FS_PUTNAME_ADDR = ${TEMP2[0]}"
echo "#define FS_PUTNAME_ADDR 0x${TEMP2[0]}" >> offsets.h

TEMP=`sudo grep " getname$" /proc/kallsyms`
TEMP2=($TEMP)
echo "Setting FS_GETNAME_ADDR = ${TEMP2[0]}"
echo "#define FS_GETNAME_ADDR 0x${TEMP2[0]}" >> offsets.h
